version: '3.9'
name: url-shortener

services:

  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    restart: always

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: my-redis-insight
    ports:
      - "8001:8001"
    environment:
      - REDIS_URI=redis://redis:6379
  # seq:
  #     image: datalust/seq:latest
  #     container_name: seq
  #     environment:
  #       - ACCEPT_EULA=Y
  #     volumes:
  #       - seq_data:/data
  #     ports:
  #       - "17780:80"

volumes:
  rabbitmq_data:
  redis-data: #seq_data:
